# User
user : 'astella'
# Experiment
experiment : 'SexualImprinting'
# Experimental group
experimental_group : 'C57_MaleUrine_Exposure_cFos'
# mouse
subjects : ['F1Control', 'F2Unfam']

# resampling parameters
source_res : [1.626, 1.626, 5]
sink_res : [25,25,25]

# orientation of the brain
orientation : [1,2,3]

# test data parameters
# slicing
slice_x : [2900, 3100]
slice_y : [4120, 4320]
slice_z : [620,650]

# parameters for detection
shape_param : !!python/tuple [7,7]
shape_detection_threshold : 700

# parameters for filtering
source : !!python/tuple [10, 5000]
size : !!python/tuple [20,100]

# parameters for voxelization
method : 'sphere'
radius : [7,7,7]

# rerun and debugging options
rerun_alignment : True
debug_detection : False
